name: MLOps Pipeline

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start app
        run: |
          pip3 install --no-cache-dir -r requirements.txt
          
          python3 app.py &
          sleep 5 # give server a few seconds to start

      - name: App health check
        run: |
          RESPONSE=$(curl -s http://localhost:8080/)
          if [ "$RESPONSE" != "Welcome to our flask api(base)" ]; then
            echo "Health check failed, got '$RESPONSE'"
            exit 1
          fi          

  build-and-push:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest

    steps:

      - name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to dockerhub
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME_TAG }}/express-hello:latest
